module CarSystem(SB,DOOR,KEY,BRK,PARK,HOOD,BAT_OK,AIB_OK,TMP_OK,PASS_OCC,SB_P,TRUNK,PBRK,SRV
                START_PERMIT, CHIME, WARN_PRI2, WARN_PRI1,SEAT_WARN,DOOR_WARN,HOOD_WARN,TRUNK_WARN,BAT_WARN,AIRBAG_WARN,TEMP_WARN);
  input SB,DOOR,KEY,BRK,PARK,HOOD,BAT_OK,AIB_OK,TMP_OK,PASS_OCC,SB_P,TRUNK,PBRK,SRV;
  output START_PERMIT, CHIME, WARN_PRI2, WARN_PRI1,SEAT_WARN,DOOR_WARN,HOOD_WARN,TRUNK_WARN,BAT_WARN,AIRBAG_WARN,TEMP_WARN;

  assign START_PERMIT
  assign CHIME
  assign WARN_PRI2
  assign WARN_PRI1
    assign SEAT_WARN = (~SB & ~SB_P & PASS_OC) | (~SB & SB_P & PASS_OC) | 
  assign DOOR_WARN = ~DOOR;
  assign HOOD_WARN = ~HOOD:
  assign TRUNK_WARN = ~TRUNK;
  assign BAT_WARN = ~BAT_OK;
  assign AIRBAG_WARN = ~AIB_OK;
  assign TEMP_WARN = ~TMP_OK;
  
