module top4(SB,DOOR,KEY,BRK,PARK,HOOD,BAT_OK,AIB_OK,TMP_OK,PASS_OCC,SB_P,TRUNK,PBRK,SRV
                START_PERMIT, CHIME, WARN_PRI2, WARN_PRI1,SEAT_WARN,DOOR_WARN,HOOD_WARN,TRUNK_WARN,BAT_WARN,AIRBAG_WARN,TEMP_WARN);
  input SB,DOOR,KEY,BRK,PARK,HOOD,BAT_OK,AIB_OK,TMP_OK,PASS_OCC,SB_P,TRUNK,PBRK,SRV;
  output START_PERMIT, CHIME, WARN_PRI2, WARN_PRI1,SEAT_WARN,DOOR_WARN,HOOD_WARN,TRUNK_WARN,BAT_WARN,AIRBAG_WARN,TEMP_WARN;

  CarSystem cs(.SB(SB),.DOOR(DOOR),.KEY(KEY),.BRK(BRK),.PARK(PARK),.HOOD(HOOD),.BAT_OK(BAT_OK),.AIB_OK(AIB_OK),.TMP_OK(TMP_OK),.PASS_OCC(PASS_OCC),.SB_P(SB_P),.TRUNK(TRUNK),.PBRK(PBRK),.SRV(SRV),
               .START_PERMIT(START_PERMIT),.CHIME(CHIME),.WARN_PRI2(WARN_PRI2),.WARN_PRI1(WARN_PRI1),.SEAT_WARN(SEAT_WARN),.DOOR_WARN(DOOR_WARN),.HOOD_WARN(HOOD_WARN),.TRUNK_WARN(TRUNK_WARN),.BAT_WARN(BAT_WARN),.AIRBAG_WARN(AIRBAG_WARN),.TEMP_WARN(TEMP_WARN));

endmodule
  
